### ISSUE TITLE
22.04: upgrading from 20.04 requires upgrading twice

### ISSUE THREAD

**Issue by leviport** [pop-os/upgrade#273] opened 2022-03-30 23:26 UTC
If I run `pop-upgrade release upgrade -f` on 20.04, it upgrades me to 21.10 instead of 22.04. I would expect the `-f` flag to allow it to upgrade straight to 22.04.

**Comment by XV-02** [comment] 2022-04-18 21:58
Following the directions for getting https://github.com/pop-os/upgrade/pull/225 up and going, 20.04 **failed** to upgrade directly to 22.04 several times.

`pop-upgrade` reports that it successfully updates the recovery partition, but seems to arbitrarily stop after that. On one occasion, it stopped immediately after reporting a successful upgrade of the recovery partition, on another, it progressed through  majority of the fetch operations it processes after that. I've attached the `journalctl` log filtered for `pop-upgrade` related entries for a third failure, in which it stopped spontaneously after this point (from the terminal):

```system76@pop-os:~$ pop-upgrade release upgrade -f
checking if pop-upgrade requires an update
Current Release: 20.04
Upgrading to: 22.04
New version available: 2
Recovery event: fetching recovery files
Fetched 3123/3123 MiB
Recovery event: verifying checksums of fetched files
Recovery event: syncing recovery files with recovery partition
Recovery event: recovery partition upgrade completed
Recovery upgrade status: recovery partition refueled and ready to go
Event: updating package lists
Event: fetching updated packages for the current release
Fetched (1/25): sessioninstaller_0.20+pop0~1646352199~20.04~c50c1a0_all.deb
Fetched (2/25): ubuntu-release-upgrader-core_1.0.0~1646945775~20.04~86da11d_amd64.deb
```

[JCTLpopupgrade.txt](https://github.com/pop-os/upgrade/files/8508383/JCTLpopupgrade.txt)

**Comment by XV-02** [comment] 2022-04-18 22:01
As an addendum:

It appears that the recovery partition is correctly upgraded and that a refresh install from the recovery partition works.

**Comment by mmstick** [comment] 2022-04-18 22:02
I'm seeing this:

```
Apr 18 15:17:36 pop-os pop-upgrade[13207]: The following held packages will be changed:
Apr 18 15:17:36 pop-os pop-upgrade[13207]:   pop-upgrade
Apr 18 15:17:36 pop-os pop-upgrade[13207]: The following packages will be DOWNGRADED:
Apr 18 15:17:36 pop-os pop-upgrade[13207]:   libpop-upgrade-gtk pop-upgrade
Apr 18 15:17:36 pop-os pop-upgrade[13207]: 0 upgraded, 0 newly installed, 2 downgraded, 0 to remove and 25 not upgraded.
Apr 18 15:17:36 pop-os pop-upgrade[13207]: E: Held packages were changed and -y was used without --allow-change-held-packages.
Apr 18 15:17:36 pop-os systemd[1]: pop-upgrade.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 15:17:36 pop-os systemd[1]: pop-upgrade.service: Failed with result 'exit-code'.
```

**Comment by XV-02** [comment] 2022-04-18 22:17
Is there a way to resolve that which should notionally enable the direct hop between LTS releases?

**Comment by mmstick** [comment] 2022-04-18 22:19
I'm looking into what might be causing this, but this only happens from 20.04?

**Comment by XV-02** [comment] 2022-04-18 22:23
I'll double check 21.10. It worked previously, but with the changes since it probably represents a good idea to look again.

**Comment by mmstick** [comment] 2022-04-18 22:28
I think this is an easy fix. Something is calling `UpdateCheck` while the upgrade is already in progress. The daemon shouldn't restart while it's mid-upgrade.

**Comment by mmstick** [comment] 2022-04-18 22:49
A patch is in the `schedule` branch now

**Comment by XV-02** [comment] 2022-04-18 22:53
With 21.10, `pop-upgrade release upgrade -f` also updates the recovery partition correctly, but hangs, with journalctl showing it stuck at:

```
Apr 18 16:39:19 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:825: Sending DBus Event: Fetching(
Apr 18 16:39:19 pop-os pop-upgrade[20801]:     "http://apt.pop-os.org/release/pool/impish/system-updater/44748b79ed1bff2eb0d2880642f7e905be6b422d/pop-system-updater_0.1.0%7e1649205922%7e21.10%7e44748b7_amd64.deb",
Apr 18 16:39:19 pop-os pop-upgrade[20801]: )
Apr 18 16:39:20 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:724: status 3:2
[...]
Apr 18 16:39:40 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:724: status 3:2
Apr 18 16:39:40 pop-os pop-upgrade[20801]: [INFO ] release/mod.rs:284: pop-system-updater_0.1.0~1649205922~21.10~44748b7_amd64.deb: retrying fetch
Apr 18 16:39:41 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:724: status 3:2
[...]
Apr 18 16:40:04 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:724: status 3:2
Apr 18 16:40:04 pop-os pop-upgrade[20801]: [INFO ] release/mod.rs:284: pop-system-updater_0.1.0~1649205922~21.10~44748b7_amd64.deb: retrying fetch
Apr 18 16:40:05 pop-os pop-upgrade[20801]: [DEBUG] daemon/mod.rs:724: status 3:2
```

I've added the `[...]` for brevity, as it's just repetition for the immediately proceeding log entry for about 20 lines each time. It keeps attempting the fetch to no avail.

[JCTL2110popupgrade.txt](https://github.com/pop-os/upgrade/files/8508594/JCTL2110popupgrade.txt)

**Comment by mmstick** [comment] 2022-04-18 23:14
I've pushed a change that should update the package lists after a few failed attempts to try again.

**Comment by jacobgkau** [comment] 2022-04-19 02:54
I was not able to recreate this issue on a 20.04 EFI VM today. @XV-02 Could you check if the issue is fixed with your testing sequence on newer pop-upgrade builds?

**Comment by XV-02** [comment] 2022-04-19 16:20
@mmstick It's looking promising. I'm seeing some output after reaching the reboot instruction though:
`[ERROR] client/mod.rs:350: breaking connection to pop-upgrade daemon due to inactivity`
I'm going to run through it a couple more times, just to make sure it's performing functionally, but it's looking good.

**Comment by XV-02** [comment] 2022-04-19 17:13
Nope. Aborted on subsequent run throughs. Same issue multiple times.

Terminal output (truncated to just the end):
```
Setting up update-manager-core
Progress: 85%
Progress: 92%
Processing triggers for dbus
Event: ensuring that system-critical packages are installed
Event: updating the source lists
Event: waiting on a process holding the apt lock files
Event: updating package lists
Event: updating package lists
Event: fetching packages for the new release
Release upgrade status: release upgrade aborted: failed to fetch apt URIs to fetch
```

And the journalctl log for pop-upgrade:
[JCTLpopupgrade19042022-1.txt](https://github.com/pop-os/upgrade/files/8515070/JCTLpopupgrade19042022-1.txt)

**Comment by mmstick** [comment] 2022-04-19 18:09
```
daemon/mod.rs:837: release upgrade: fetching packages for the new release
E: Unable to correct problems, you have held broken packages.
```

Seems there was a package conflict detected?

**Comment by XV-02** [comment] 2022-04-19 18:35
What's the best way to go about diagnosing that? I haven't marked any packages to be explicitly held, but I don't know if the system would hold anything. None of the update-upgrade actions flagged anything as not being upgraded. The process isn't verbose enough for me to try and figure out what it breaking from being held.

**Comment by mmstick** [comment] 2022-04-19 18:46
I'll do some testing in a VM to verify if some changes I made might have fixed it

**Closed** 2022-04-20 23:03 UTC
