### ISSUE TITLE
Upgrade failed from 21.04 to 21.10 

### ISSUE THREAD

**Issue by razvan01** [pop-os/upgrade#257] opened 2021-12-16 21:34 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

python3:
  Installed: 3.9.4-1
  Candidate: 3.9.4-1
  Version table:
 *** 3.9.4-1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
systemd:
  Installed: 247.3-3ubuntu3.6pop0~1631829388~21.04~08ab711
  Candidate: 247.3-3ubuntu3.6pop0~1631829388~21.04~08ab711
  Version table:
 *** 247.3-3ubuntu3.6pop0~1631829388~21.04~08ab711 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
     247.3-3ubuntu3.6 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
     247.3-3ubuntu3.4 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-security/main amd64 Packages
     247.3-3ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
base-files:
  Installed: 11ubuntu19
  Candidate: 11ubuntu19
  Version table:
 *** 11ubuntu19 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

After upgrade try from settings it failed.

**Steps to reproduce (if you know):**

Upgrade from Settings -> OS Upgrade (failed)
Switch to terminal:
apt update
apt full-upgrade
Tried also dpkg --configure -a and apt -f install without success

**Expected behavior:**

Upgrade to Pop OS 21

**Other Notes:**

I've also tried to remove status file but without success.

**Comment by jacobgkau** [comment] 2022-01-24 22:18
https://github.com/pop-os/upgrade/pull/244 included many fixes for dependency situations where the candidate version needs to be specified or overridden. The version including that fix, 788fc60, was finally released on 21.04 today (it was released on 20.04 and 18.04 last week.) Closing this issue & any new occurrences (on machines where the upgrade was not previously attempted) will need to be triaged separately.

As a reminder, steps to recreate an issue starting from a fresh installation of Pop!_OS are required in order to completely guarantee that a particular case will be handled correctly.

**Closed by jacobgkau** 2022-01-24 22:18 UTC

**Comment by illtellyoulater** [comment] 2023-09-15 07:43
Hi, 
I am on Pop!_OS 22.04 (LTS x86_64 ) 
with Kernel 6.4.6-76060406-generic 

and was getting exactly the same issue reported by everyone else in this thread, and I found what is the unfortunate precise sequence of events leading to our error.

- this indeed begins with the pop-update command  (either when scheduled to run, or when triggered in response to hitting the recovery image download button (as in my case,   after being disabled for like 2 months) .

So I clicked and as a soon it was completed, asbegan the actual update operation failed with  this error:

Recovery update failed: Failed to mount recovery ISO  caused by: \n  No such device  (os error 19);

So I tried replaying the whole procedure and error in the console with:

journalctl pop-ugrade

which basically showed how for some reason the update code make a call to pipewire which in turn calls speech-dispatcher 

as documented for by everyone in this thread... 

but then speech-dispatcher tries to so something by squiring a lock on it, and this is exactly where it fails generating the "recovery update failed: failed to mount recovery ISO Caused by No such device  (os error 19)"

As for a final verification, I went in /var/lib/apt/lists/ and I could find the lock file, expected. 
Finally,  I ran a command for examining which processes are currently stuck because of a locked files, (lslocks -i -o COMMAND)  and I get exactly: 

pipewire
speech-dispatch

Now, I have no idea why those 2 commands are called , but you surely do, so please  please, after all this analysis can you  come up with a fix?

If you guys you searched for these terms on Reddit you'll find out how many of your user are being affected by tat every upgrade... which end up rebooting and needing to reinstall the system completely, because this is somehow leaving the recovery image in a damaged state.

@razvan01 
@jacobgkau 
( or anyone else at or anyone else at Pop!_OS  )

Not sure why I and others are facing this weird problem but.. it's clearly a disaster just waiting to happen and I for first don't know what to do right now. This has to be addressed guys.
Please step up and do something about it.
