### ISSUE TITLE
CLI upgrade from 18.10 to 19.10 upgrade to ubuntu

### ISSUE THREAD

**Issue by Artofaj** [pop-os/upgrade#17] opened 2019-04-19 08:37 UTC
I just finished up upgrading via cli using ``do-release-upgrade`` after the restart the pop-icon theme was gone so I opened terminal to check the upgrade. The pop terminal theme is gone aswell. And neofetch shows the following:

![Screenshot from 2019-04-19 10-38-44](https://user-images.githubusercontent.com/39367453/56415936-9750a180-628f-11e9-8273-1681c26a1307.png)

**Comment by Artofaj** [comment] 2019-04-19 19:34
I clean installed. The problem persists.

**Comment by mmstick** [comment] 2019-04-19 19:41
I'm closing this because the issue isn't related to `pop-upgrade`.
However, I will mention that this issue will be fixed once [this PR is merged](https://github.com/pop-os/default-settings/pull/56).

**Closed by mmstick** 2019-04-19 19:41 UTC
