### ISSUE TITLE
Keyboard input sources (language) reset after an upgrade

### ISSUE THREAD

**Issue by strudelPi** [pop-os/upgrade#191] opened 2021-07-12 08:13 UTC
Hey folks, 

System Settings -> Keyboard -> Input Sources

this is probably just a minor thing but after upgrading my pop os to 21.04 my keyboard setup (Czech QWERTY) seemed to reset. It's just the missing keyboard layout setting in there, nothing else not working. 

After figuring out I can't switch there because of this and not because the keybinding for switching is broken I just added it again and it works just fine :+1:

**Comment by leviport** [comment] 2021-07-12 16:08
This looks like a duplicate of https://github.com/pop-os/pop/issues/1753

**Closed by leviport** 2021-07-12 16:08 UTC
