### ISSUE TITLE
ppp/libnm0 dependency issues

### ISSUE THREAD

**Issue by ikohlernz** [pop-os/upgrade#256] opened 2021-12-15 07:32 UTC
**Distribution**:

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

pop-upgrade: calling FetchUpdates method failed
  caused by: failed to exec `apt-get full-upgrade --print-uris`: status is unknown: exit status: 100

apt-get full-upgrade --print-uris
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 network-manager : Depends: libnm0 (= 1.30.0-1ubuntu3) but 1.32.12-0ubuntu1 is installed
                   Recommends: ppp but it is not installed
                   Recommends: modemmanager but it is not installed
 network-manager-l2tp : Depends: ppp (< 2.4.7-3~) but it is not installed
                        Depends: ppp (>= 2.4.7-2+~) but it is not installed
 network-manager-pptp : Depends: ppp (< 2.4.7-3~) but it is not installed
                        Depends: ppp (>= 2.4.7-2+~) but it is not installed
 pptp-linux : Depends: ppp but it is not installed
 xl2tpd : Depends: ppp but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

apt policy network-manager
network-manager:
  Installed: 1.30.0-1ubuntu3
  Candidate: 1.30.0-1ubuntu3
  Version table:
 *** 1.30.0-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
    
 pop-os:~$ apt policy ppp
ppp:
  Installed: (none)
  Candidate: 2.4.7-2+4.1ubuntu8
  Version table:
     2.4.9-1+1ubuntu1 -1
        100 /var/lib/dpkg/status
     2.4.7-2+4.1ubuntu8 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages

       
pop-os:~$ apt policy libnm0
libnm0:
  Installed: 1.32.12-0ubuntu1
  Candidate: 1.32.12-0ubuntu1
  Version table:
 *** 1.32.12-0ubuntu1 100
        100 /var/lib/dpkg/status
     1.30.0-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages

pop-os:~$ apt policy network-manager-pptp
network-manager-pptp:
  Installed: 1.2.8-3
  Candidate: 1.2.8-3
  Version table:
 *** 1.2.8-3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:** After trying to update to 21.10 via the gui pop up,  it never finished. Might have been interrupted during the process.  Laptop rebooted and afterwards trying to update anything fails, I can now see dependency errors, tried a number of things, but cannot get pass it. 
Tried suggested fix:

sudo apt clean
sudo apt update -m
sudo dpkg --configure -a
sudo apt install -f
sudo apt dist-upgrade
sudo apt autoremove --purge

But any apt get command fails now.

Similar issue also reported during beta testing by someone else : https://githubmemory.com/repo/pop-os/beta/issues/238

**Steps to reproduce:**

Have Pop 21.04 up to date
Tried to download/upgrade the PopOS21.10 that never finished.
Then facing the dependency error.

Expected behavior:

Pop! OS is upgraded from 21.04 to 21.10.

**Comment by jacobgkau** [comment] 2022-01-24 22:14
https://github.com/pop-os/upgrade/pull/244 included fixes for ppp/libnm0 dependency issues. The version including that fix, 788fc60, was finally released on 21.04 today (it was released on 20.04 and 18.04 last week.) Closing this issue & any new occurrences will have to be triaged separately.

**Closed by jacobgkau** 2022-01-24 22:14 UTC

**Comment by fluidvoice** [comment] 2022-02-22 19:11
> #244 included fixes for ppp/libnm0 dependency issues. The version including that fix, [788fc60](https://github.com/pop-os/upgrade/commit/788fc604e96caf0c130dc7f85535461112fb74d6), was finally released on 21.04 today (it was released on 20.04 and 18.04 last week.) Closing this issue & any new occurrences will have to be triaged separately.

That's great, but how do people install it?  

![Screenshot from 2022-02-22 16-10-16](https://user-images.githubusercontent.com/373038/155202049-e168c0fb-1bb9-45be-aabb-a3b913f638c7.png)

**Comment by jacobgkau** [comment] 2022-02-22 19:32
> That's great, but how do people install it?

You should already have it, unless you first attempted to install the upgrade before 1/24. pop-upgrade self-updates itself whenever it's run, and effectively on every boot when it checks for update notifications. Please provide the output of `apt policy pop-upgrade` to confirm.

From my comment:

> any new occurrences will have to be triaged separately.

This means a new issue page would be appropriate if you did not attempt the upgrade prior to today and still had the issue (although the issue will only be actionable if it includes enough information to recreate from a fresh system and/or identifies the root cause.)
